/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendanceList: typeof import('./src/components/Ggomoosin/HR/AttendanceList.vue')['default']
    Customers: typeof import('./src/components/TienNga/MaterialPurchasing/Customers.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    EmployeeList: typeof import('./src/components/Ggomoosin/HR/EmployeeList.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/auth/ForgotPasswordForm.vue')['default']
    FormInput: typeof import('./src/components/auth/FormInput.vue')['default']
    FundDetail: typeof import('./src/components/TienNga/Finance/FundDetail.vue')['default']
    FundList: typeof import('./src/components/TienNga/Finance/FundList.vue')['default']
    Households: typeof import('./src/components/TienNga/RubberPurching/Households.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Index: typeof import('./src/components/Ggomoosin/HR/Index.vue')['default']
    InformationLookup: typeof import('./src/components/TienNga/Partner/InformationLookup.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LoginView: typeof import('./src/components/auth/LoginView.vue')['default']
    Overall: typeof import('./src/components/TienNga/Overall.vue')['default']
    PartnerList: typeof import('./src/components/TienNga/Partner/PartnerList.vue')['default']
    Payment: typeof import('./src/components/TienNga/RubberPurching/Payment.vue')['default']
    PrimaryButton: typeof import('./src/components/auth/PrimaryButton.vue')['default']
    ProductWarehouseDetail: typeof import('./src/components/TienNga/ProductWarehouse/ProductWarehouseDetail.vue')['default']
    ProductWarehouseList: typeof import('./src/components/TienNga/ProductWarehouse/ProductWarehouseList.vue')['default']
    Purchasing: typeof import('./src/components/TienNga/MaterialPurchasing/Purchasing.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalaryExport: typeof import('./src/components/Ggomoosin/HR/SalaryExport.vue')['default']
    SalaryList: typeof import('./src/components/Ggomoosin/HR/SalaryList.vue')['default']
    Sidebar: typeof import('./src/components/Ggomoosin/Sidebar.vue')['default']
    Transaction: typeof import('./src/components/TienNga/Partner/Transaction.vue')['default']
    WarehouseDetail: typeof import('./src/components/TienNga/Warehouse/WarehouseDetail.vue')['default']
    WarehouseList: typeof import('./src/components/TienNga/Warehouse/WarehouseList.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
